### ISSUE TITLE
chrome 浏览器点不开用不了

### ISSUE THREAD

**Issue by natamox** [PengChen96/ajax-tools#1]
版本 108.0.5359.124（正式版本） (x86_64)

**Comment by PengChen96** [comment]
https://chrome.google.com/webstore/detail/ajax-interceptor-tools/kphegobalneikdjnboeiheiklpbbhncm?hl=zh-CN&authuser=0
是这个0.0.3版本吗，你安装后刷新下页面，页面加载完再点击试试呢

**Comment by natamox** [comment]
> https://chrome.google.com/webstore/detail/ajax-interceptor-tools/kphegobalneikdjnboeiheiklpbbhncm?hl=zh-CN&authuser=0 是这个0.0.3版本吗，你安装后刷新下页面，页面加载完再点击试试呢

可以了，挺好用的，收下我的star吧
