### ISSUE TITLE
无法修改request的payload

### ISSUE THREAD

**Issue by yepisu** [PengChen96/ajax-tools#10]
request payload中编写的js代码被直接当做普通文本值传递了，没有执行
edge版本： 119.0.2151.72
edge插件版本：0.0.8
chrome版本：119.0.6045.160
chrome插件版本：0.0.8

![11](https://github.com/PengChen96/ajax-tools/assets/25145769/ef3505ac-54fd-4276-9407-06111be4c903)
![12](https://github.com/PengChen96/ajax-tools/assets/25145769/3045aaff-2ca1-45bb-86e1-e01a73c00320)
![000](https://github.com/PengChen96/ajax-tools/assets/25145769/26abb3f0-54f8-4d60-91d1-dd3c90ebc527)
![21](https://github.com/PengChen96/ajax-tools/assets/25145769/259126b6-b60a-44c5-bc7c-d037f1b56459)
![22](https://github.com/PengChen96/ajax-tools/assets/25145769/6c7245b1-4c23-412d-9cca-7f5dab910b84)

**Comment by PengChen96** [comment]
好的，我复现下，你这个接口是POST还是GET请求，请求体是FormData吗

**Comment by yepisu** [comment]
> 好的，我复现下，你这个接口是POST请求吗，请求体是FormData吗

是post，是form

腾讯新闻 https://news.qq.com/ch/tech/ 有个post请求 https://i.news.qq.com/gw/pc_search/hotWord
可以用这个测一下。
![Snipaste_2023-11-22_17-27-10](https://github.com/PengChen96/ajax-tools/assets/25145769/9de6faba-b5ff-40d2-98a7-2e210b0019e3)

**Comment by PengChen96** [comment]
<img width="287" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/691bb897-c3fd-488b-b2e4-08ebab29aafb">   

我打了断点看了这个接口，发现他的参数是这样的，并不是FormData对象，所以你可以往后拼参数去修改。  

你改成这样就可以了  
<img width="347" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/d7531afe-8ee9-4557-89f3-2bd1c83d5c78">
