### ISSUE TITLE
介绍页面的SSL证书已过期，请重新颁发

### ISSUE THREAD

**Issue by shunop** [PengChen96/ajax-tools#15]
访问 https://doc.yilijishu.info/chrome/declarativeNetRequest.html 时，发现站点的 SSL 证书已过期

<img width="544" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/74529141/53cd52f3-9d7c-419a-9799-4649feb11c8a">

**Comment by PengChen96** [comment]
你这个是从哪里进行访问的，该插件并没有这个域名，正常应该是这个chrome-extension://gpnmkbkbpiiloealoigebebohbgikdig/html/iframePage/dist/declarativeNetRequest.html

**Comment by PengChen96** [comment]
这个文档不是我的站点[捂脸]
