### ISSUE TITLE
会影响其乐(keylol)论坛的收藏和回帖功能

### ISSUE THREAD

**Issue by CrystalFairy** [PengChen96/ajax-tools#18]
问题描述
其乐论坛收藏和回帖后无反应，实际已经成功，控制台报错如下：
![image](https://github.com/PengChen96/ajax-tools/assets/50792200/04f97018-f17d-400e-b664-25b675e1101c)

复现步骤
如何复现
1. 打开其乐论坛keylol.com，并登录
2. 点击收藏或回帖
3. 无反应，控制台报错

截图
收藏：
![收藏](https://github.com/PengChen96/ajax-tools/assets/50792200/7e9479a8-0996-4f17-94bb-0f478e1292b3)
回帖：
![回帖](https://github.com/PengChen96/ajax-tools/assets/50792200/4d15e0ec-0158-4b5a-9272-10819d18152d)

环境信息
- 系统版本：windows10专业版 21H2 19044.2846
- 插件版本：0.0.10
- 浏览器版本：Chrome 124.0.6367.158

**Comment by PengChen96** [comment]
我排查了下是注入js、css这些，会注入到这个网站的iframe里然后冲突了，我修改了下应该可以了，你可以安装下面这个链接的版本，https://github.com/PengChen96/ajax-tools/blob/master/kphegobalneikdjnboeiheiklpbbhncm.crx

**Comment by CrystalFairy** [comment]
> 我排查了下是注入js、css这些，会注入到这个网站的iframe里然后冲突了，我修改了下应该可以了，你可以安装下面这个链接的版本，https://github.com/PengChen96/ajax-tools/blob/master/kphegobalneikdjnboeiheiklpbbhncm.crx

万分感谢大佬，测试已经正常了。
