### ISSUE TITLE
您好，请问下载代码可以运行吗？

### ISSUE THREAD

**Issue by wangziyang0649** [PengChen96/ajax-tools#2]
我下载代码安装之后，启动插件提示：“该文件可能已被移至别处、修改或删除。”，请问是缺少什么文件吗，谢谢

**Comment by PengChen96** [comment]
需要打包一下的，你进到html/iframePage目录下，安装一下依赖，打包生成dist，然后把ajax-tools文件夹拖进Chrome这样就可以了
