### ISSUE TITLE
修改不了返回值，是我配置的不对吗

### ISSUE THREAD

**Issue by dooonabe** [PengChen96/ajax-tools#21]
目标网站：https://artist.mnetplus.world/main/stg/zerobaseone/surveys/66449133d2620e1f8f5810a2

目标接口：get https://artist.mnetplus.world/svc/stg/zerobaseone/live-streaming/api/v1/circles/new

**Comment by dooonabe** [comment]
https://ts.javascript6.cn:18880/20240516143917.png
https://ts.javascript6.cn:18880/20240516144920.png

**Comment by PengChen96** [comment]
<img width="429" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/b401648b-75a7-4c75-939c-8ead5b4a6c0b">
我试了是能修改成功的，页面没效果可能是还有其他原因。

**Comment by dooonabe** [comment]
好，我再看看
