### ISSUE TITLE
你好，请问可以修改html页面引用的js文件内容嘛

### ISSUE THREAD

**Issue by champkeh** [PengChen96/ajax-tools#4]

**Comment by PengChen96** [comment]
你好，js文件内容目前是不支持修改的，不过你可以通过下面这个页面去把js地址重定向到你本地这样。
chrome-extension://kphegobalneikdjnboeiheiklpbbhncm/html/iframePage/dist/declarativeNetRequest.html

**Comment by champkeh** [comment]
![image](https://github.com/PengChen96/ajax-tools/assets/7316006/311521ba-4f8e-4e47-83a5-175a913c1ac1)

比如，我想把 www.example.com 域名下的所有js文件请求都重定向到我本地的 localhost:8000 上面，这样的配置有问题吗？

**Comment by champkeh** [comment]
我看官方文档上面写着不允许重定向脚本呀，上面这个配置好像也没效果

https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-Redirect:~:text=Redirects%20to%20JavaScript%20urls%20are%20not%20allowed.

**Comment by champkeh** [comment]
我目前的需求就是，有一个网站，它的js里面混入了防止调试的代码，我想把这个代码去掉。
不知道有什么方法能做到这个

**Comment by PengChen96** [comment]
端口有个port参数，试试这个：
`[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8080",
          "scheme": "http"
        }
      },
      "type": "redirect"
    },
    "condition": {
      "domains": [
        "www.example.com"
      ],
      "resourceTypes": [
        "script"
      ]
    }
  }
]`

**Comment by champkeh** [comment]
用这个配置没有效果，也不会报错，加载的脚步是原始的脚本
```js
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8000",
          "scheme": "http"
        }
      }
    },
    "condition": {
      "domains": ["midas.gtimg.cn"],
      "resourceTypes": ["script"]
    }
  }
]
```


然后用下面这个(脚本路径写全)会导致脚本加载失败
```js
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8000",
          "scheme": "http"
        }
      }
    },
    "condition": {
      "urlFilter": "https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js",
      "resourceTypes": ["script"]
    }
  }
]
```

![image](https://github.com/PengChen96/ajax-tools/assets/7316006/be9deef8-d5b2-4fce-87fd-8c2e62c7a18c)

**Comment by champkeh** [comment]
会不会是不支持重定向js文件呢

**Comment by PengChen96** [comment]
scheme改成https，试试这样行不行，我这边找了网站试了下地址是替换了
```json
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8080",
          "scheme": "http"
        }
      },
      "type": "redirect"
    },
    "condition": {
      "domains": [
        "www.example.com"
      ],
      "resourceTypes": [
        "script"
      ]
    }
  }
]
```

**Comment by champkeh** [comment]
```js
[
  {
    "action": {
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "443",
          "scheme": "https"
        }
      },
      "type": "redirect"
    },
    "condition": {
      "resourceTypes": [
        "script"
      ],
      "urlFilter": "https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js"
    },
    "id": 1,
    "priority": 1
  }
]
```
还是不行，脚本加载失败😒

**Comment by PengChen96** [comment]
是这样子，你复制过去保存，然后刷新网站试试。
```json
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8080",
          "scheme": "https"
        }
      },
      "type": "redirect"
    },
    "condition": {
      "domains": [
        "midas.gtimg.cn"
      ],
      "resourceTypes": [
        "script"
      ]
    }
  }
]
```

**Comment by champkeh** [comment]
还是不行
另外，我本地启的https服务器是443端口呀

**Comment by PengChen96** [comment]
方便把网址发我下嘛，我晚点试试看。

**Comment by champkeh** [comment]
嗯嗯，辛苦啦

https://weread.qq.com/web/reader/c5c32170813ab7177g0181ae

我把这个页面的js文件都下载到本地了，然后改了一点内容，但页面加载的还是未改动的版本

**Comment by champkeh** [comment]
我发现用devtools的overrides可以解决我的问题，插件的话我感觉用重定向是走不通的

**Comment by PengChen96** [comment]
嗯嗯，overrides也可以。那个cashier.js我看重定向是重定向了，不过是报错了。我想想不知道能不能解决，不过我试了下百度的一个js是能重定向的。
<img width="596" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/ec962b57-f4f7-46a4-a158-df3c4c771cc0">
![41694053773_ pic](https://github.com/PengChen96/ajax-tools/assets/16712630/3cc40bb9-90d9-46fb-97d4-cb45d76679a4)

**Comment by champkeh** [comment]
我这也报这个错了，好像是违反了csp策略，那估计还要修改html响应里面的csp header了

**Comment by champkeh** [comment]
关于编辑器我想提一点优化建议，可以拦截页面的 Ctrl+S 快捷键保存，现在每次改完都要等待6秒才能保存

另外，会出现这个一直保持中，等了好长时间也没有显示保存成功，不知道什么原因
![image](https://github.com/PengChen96/ajax-tools/assets/7316006/962f48a9-df78-462f-8357-4e0bea505079)

**Comment by PengChen96** [comment]
嗯嗯，这个应该是报错了，可以在控制台console中查看，我改一下把错误抛出来。
改完是可以直接点击左上角的图标保存的，快捷键Ctrl+s我晚点加一下。
感谢你的建议[呲牙]

**Comment by champkeh** [comment]
感谢，我现在用这个配置可以重定向了:
```js
[
  {
    "action": {
      "responseHeaders": [
        {
          "header": "Content-Security-Policy",
          "operation": "remove"
        }
      ],
      "type": "modifyHeaders"
    },
    "condition": {
      "resourceTypes": [
        "main_frame"
      ],
      "urlFilter": "c5c32170813ab7177g0181ae"
    },
    "id": 1,
    "priority": 1
  },
  {
    "action": {
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "8080",
          "scheme": "https"
        }
      },
      "type": "redirect"
    },
    "condition": {
      "urlFilter": "cashier"
    },
    "id": 2,
    "priority": 1
  }
]
```
![image](https://github.com/PengChen96/ajax-tools/assets/7316006/718c18cc-8fd7-4961-b460-6d09380892d7)

**Comment by PengChen96** [comment]
棒👍
