### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by hfdzlsw** [PengChen96/ajax-tools#5]
我修改了 response 响应，在拿到数据后请求我本地的一个接口，但是报了跨域问题。于是我在接口上加了 Access-Control-Allow-Origin 响应头，依旧是有没有效果。抛开这个插件，我自己请求我那个接口是没有问题的

**Comment by hfdzlsw** [comment]
接口是我本地接口，不是同域，是localhost
![图片](https://github.com/PengChen96/ajax-tools/assets/11845565/874583d1-7017-4c84-9e63-139b895146c7)

**Comment by hfdzlsw** [comment]
代码：
let { originalResponse } = arguments[0];
var httpRequest = new XMLHttpRequest();
let url = "http://localhost:7001/test2";
httpRequest.open('POST', url);
httpRequest.setRequestHeader("Content-type", "application/json");
let obj = { "text": originalResponse }
httpRequest.send(JSON.stringify(obj));
/**
 * 获取数据后的处理程序
 */
httpRequest.onreadystatechange = function () {
  if (httpRequest.readyState == 4 && httpRequest.status == 200) {
    var json = httpRequest.responseText;
    console.log(json);
  }
};
return originalResponse;

**Comment by PengChen96** [comment]
这样是会跨域的，不过在插件里面这样写调用接口，拿到的结果是替换不了这个结果的。
你可以试试把你要修改的接口直接重定向到你本地接口，这样符合你的需求吗

**Comment by hfdzlsw** [comment]
我需求不需要替换响应数据的，我只要拿这个数据在我本地服务器处理就好，重定向也可以实现吗

**Comment by PengChen96** [comment]
你是想页面上点击调用接口，然后就触发你本地的接口吗，不替换响应的话可以这样写。

**Comment by hfdzlsw** [comment]
配置文件：

> [
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "host": "localhost",
          "port": "7001",
          "scheme": "http"
        }
      }
    },
    "condition": {
      "urlFilter": "xxx",
      "domains" : ["xxx"],
      "resourceTypes": ["xmlhttprequest"]
    }
  }
]

**Comment by PengChen96** [comment]
<img width="564" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/e3df5b44-d9f4-4528-a858-daf4473bdda8">
<img width="457" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/867a4609-c7b3-4b65-94f5-dd030eed5725">
你按之前的那个js代码是对的，然后只要在你的接口响应头加上"Access-Control-Allow-Origin"："https://live.kuaishou.com"和"Access-Control-Allow-Headers"："Content-Type"这样应该就可以跨域了，你试试

**Comment by hfdzlsw** [comment]
这个方法虽然成功了，但是我的 test2 是 post 请求，我在 flask 里面没有看到传递过来的响应值

**Comment by hfdzlsw** [comment]
flask代码：

> @app.route('/test2', methods=['POST'])
def test2():
    return_text = ""
    try:
        print(request.form)
        content = request.form['text']
        print(content)
    except Exception as e:
        log.info(''.join(traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)))
    return ""

**Comment by PengChen96** [comment]
你看下浏览器中的network面板是否有把参数传过去。

**Comment by hfdzlsw** [comment]
有两个请求，第一个是有带的，第二个没有

**Comment by PengChen96** [comment]
那应该就是你的flask代码问题了，你要自己排查下了。

**Comment by hfdzlsw** [comment]
谢谢，已经解决了
