### ISSUE TITLE
修改不了返回值

### ISSUE THREAD

**Issue by chitanda** [PengChen96/ajax-tools#7]
以发布的zhihu专栏文章评论为例：我试着改了下返回的评论内容但是并没有生效，请问是我的用法有问题吗？
![Snipaste_2023-10-19_10-24-09](https://github.com/PengChen96/ajax-tools/assets/8258592/9858fb2c-fce8-4055-b5fe-02dabab87f9e)

试过其他的一些网站也都没有生效

**Comment by PengChen96** [comment]
<img width="838" alt="image" src="https://github.com/PengChen96/ajax-tools/assets/16712630/cffc92ab-f8a3-4ac0-bb94-4825cd266085">
我试了是可以修改成功的，你刷新下页面试试

**Comment by chitanda** [comment]
试了下应该是和我另一款插件冲突了，卸载掉了就好了。感谢
